import { BUILDING, ZONES, ACTIONS, INJECTS, CHECKLISTS, checkCoverage } from './drill-core.js';
import { ROOMS, WALLS, SPATIAL_EQUIPMENT, DETECTOR, routeWalkthrough } from './spatial-data.js';

const esc = (value) => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function planVector({ state, room = 'studio', exit = 'A' }) {
  const route=routeWalkthrough(room,exit,state.injectIds.includes('stair'));
  const color=route.available?'#147c68':'#ba4733';
  return `<svg class="plan" xmlns="http://www.w3.org/2000/svg" width="1100" height="850" viewBox="0 0 1100 850" role="img" aria-label="Fictional Floor 07 drill plan, not emergency signage">
  <defs><pattern id="papergrid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#dce7e8" stroke-width=".4"/></pattern><marker id="routearrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="${color}"/></marker></defs>
  <rect width="1100" height="850" fill="#fbfcf9"/>
  <g font-family="Arial,sans-serif" fill="#172d37"><text x="42" y="44" font-size="15" letter-spacing="2">MUSTER / TRAINING DRAWING / F07</text><text x="42" y="85" font-size="32" font-weight="700">${esc(route.zone)} → ${esc(route.exit)}</text><text x="42" y="114" font-size="15">${route.available?'Available in this authored scenario only':'UNAVAILABLE — rejected by the Stair B scenario condition'} · diagram ${route.diagram_metres} m · authored route ${route.fixture_metres} m</text>
  <g transform="translate(100,120)"><rect x="42" y="42" width="816" height="524" fill="url(#papergrid)"/>
  ${ROOMS.map(r=>`<rect x="${r.bounds[0]}" y="${r.bounds[1]}" width="${r.bounds[2]-r.bounds[0]}" height="${r.bounds[3]-r.bounds[1]}" fill="${r.id===room?'#d5e9df':'#edf2ef'}"/><text x="${(r.bounds[0]+r.bounds[2])/2}" y="${r.bounds[1]+29}" font-size="12" text-anchor="middle" font-weight="700">${esc(r.label.toUpperCase())}</text><text x="${(r.bounds[0]+r.bounds[2])/2}" y="${r.bounds[1]+48}" font-size="11" text-anchor="middle">${r.occupants} people · ${r.width} × ${r.depth} m</text>`).join('')}
  <g fill="none" stroke="#24404c" stroke-width="2.2">${WALLS.map(([x1,y1,x2,y2])=>`<path d="M${x1} ${y1}L${x2} ${y2}"/>`).join('')}</g>
  <rect x="105" y="448" width="132" height="62" fill="#d0e3d1"/><rect x="676" y="448" width="132" height="62" fill="${state.injectIds.includes('stair')?'#f1d3cb':'#d0e3d1'}"/>
  <text x="171" y="493" font-size="13" font-weight="700" text-anchor="middle">STAIR A</text><text x="742" y="493" font-size="13" font-weight="700" text-anchor="middle">STAIR B</text>
  <text x="375" y="272" font-size="12" text-anchor="middle">FIRE LIFT</text><text x="375" y="289" font-size="10" text-anchor="middle">not a route</text>
  ${state.injectIds.includes('smoke')?'<circle cx="526" cy="296" r="24" fill="#f2d9c7" stroke="#bb6139"/><text x="526" y="301" text-anchor="middle" font-size="11">SIGNAL</text>':''}
  <path d="${route.points.map((p,i)=>`${i?'L':'M'}${p[0]} ${p[1]}`).join(' ')}" fill="none" stroke="${color}" stroke-width="4" stroke-dasharray="8 5" marker-end="url(#routearrow)"/>
  ${route.steps.map((s,i)=>`<circle cx="${s.point[0]}" cy="${s.point[1]}" r="10" fill="${i>route.maxStep?'#9babad':color}" stroke="#fff" stroke-width="2"/><text x="${s.point[0]}" y="${s.point[1]+4}" text-anchor="middle" fill="#fff" font-size="11" font-weight="700">${i+1}</text>`).join('')}
  ${SPATIAL_EQUIPMENT.map(e=>`<rect x="${e.point[0]-8}" y="${e.point[1]-8}" width="16" height="16" fill="#fff4d4" stroke="#947a43"/><text x="${e.point[0]}" y="${e.point[1]+4}" text-anchor="middle" font-size="11" font-weight="700">${e.symbol}</text>`).join('')}
  <g stroke="#6f9297" stroke-width="1"><path d="M70 50H830M70 43V57M830 43V57M46 72V535M39 72H53M39 535H53"/></g><text x="450" y="40" font-size="13" text-anchor="middle">38.00 m</text><text x="32" y="305" transform="rotate(-90 32 305)" text-anchor="middle" font-size="13">23.15 m</text>
  </g><path d="M42 712H1058" stroke="#8ba1a4"/><text x="42" y="740" font-size="13">E Extinguisher · H Hose reel · M Manual call point · P Assistance holding-point fixture</text><text x="42" y="765" font-size="13">MX-FS-07-004 / Rev 04 · dimensions from fictional drawing · doors and route geometry inferred</text><text x="42" y="797" font-size="16" font-weight="700" fill="#a3402e">NOT AN APPROVED ESCAPE PLAN. DO NOT DISPLAY AS EMERGENCY SIGNAGE.</text><text x="42" y="824" font-size="12">Numbers match the walkthrough. A line to a stair is not proof of a safe onward route or successful evacuation.</text></g></svg>`;
}

export function drillPackHTML(options) {
  const {state,room='studio',exit='A'}=options;
  const route=routeWalkthrough(room,exit,state.injectIds.includes('stair'));
  const coverage=checkCoverage(state);
  const assisted=state.decisions.some(d=>d.actionId==='assist');
  const stamp=new Date().toISOString().replace('T',' ').slice(0,19)+' UTC';
  const head=(number,title)=>`<header><div class="brand">M<span>MUSTER / FACILITATOR PACK</span></div><div class="stamp">F07 · REV 04<br/>${stamp}</div></header><div class="title"><span>0${number} / FICTIONAL TABLETOP EXERCISE</span><h1>${title}</h1></div>`;
  const foot=(n)=>`<footer><b>TRAINING ONLY · NOT FOR LIVE EMERGENCIES</b><span>muster-fire-drill.vercel.app · ${n}/2</span></footer>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/><title>Muster F07 drill pack</title><style>
  *{box-sizing:border-box}body{margin:0;background:#d5dfdf;color:#182e38;font-family:Arial,sans-serif}button{font:inherit}.page{width:400mm;height:275mm;margin:10mm auto;padding:10mm 12mm;background:#fbfcf9;position:relative;overflow:hidden}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #bbc9c9;padding-bottom:5mm}.brand{display:flex;align-items:center;gap:3mm;font-size:28px;font-weight:900}.brand span{font-size:10px;letter-spacing:1.4px}.stamp{font:10px monospace;text-align:right;line-height:1.6;color:#536e76}.title{margin:6mm 0 4mm}.title>span{color:#49756c;font:10px monospace;letter-spacing:1px}h1{font-size:32px;letter-spacing:-1px;margin:2mm 0}h2{font-size:18px;margin:0 0 3mm}p{font-size:12px;line-height:1.5;margin:2mm 0}.spread{display:grid;grid-template-columns:2.4fr 1fr;gap:8mm}.plan{width:100%;height:auto;max-height:191mm}.steps{display:grid;gap:3mm}.step{display:grid;grid-template-columns:22px 1fr;gap:8px;border-top:1px solid #becfca;padding-top:3mm}.step b{font-size:13px}.step i{font:15px monospace;color:#237862}.step p{font-size:11px;color:#4c626a}.flag{padding:3mm 4mm;background:#e8eddf;border-left:3px solid #7a8e46;font-size:11px;line-height:1.5}.reject{background:#f4e1d9;border-color:#b15339}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:4mm;margin:4mm 0 6mm}.facts div{border-top:2px solid #214c51;padding-top:3mm}.facts strong,.facts span{display:block}.facts strong{font-size:26px}.facts span{font-size:10px;margin-top:2mm;color:#59707a}.columns{display:grid;grid-template-columns:1fr 1fr;gap:7mm}.block{margin-bottom:5mm}table{width:100%;border-collapse:collapse;font-size:11px}th,td{text-align:left;padding:2.4mm 2mm;border-bottom:1px solid #ccd7d5}th{font-size:9px;text-transform:uppercase;letter-spacing:.4px;color:#507078}ul,ol{padding-left:5mm;font-size:11px;line-height:1.6;margin:2mm 0}.check{padding:2mm 0;border-bottom:1px solid #d4ddda;font-size:11px}.check:before{content:'□';margin-right:8px}footer{position:absolute;bottom:7mm;left:12mm;right:12mm;border-top:1px solid #bdceca;padding-top:3mm;display:flex;justify-content:space-between;font-size:9px;color:#5b6f74}.source{font-size:9px;color:#5a737a}.logic{border-top:1px solid #a3b9b2;padding:2mm 0}.logic b{font:10px monospace;color:#286c5e}.logic p{font-size:11px}.blank{height:11mm;border-bottom:1px dashed #9faea9;color:#829490;font-size:10px;padding-top:4mm}.toolmeta{font:9px monospace;color:#4d6b75;overflow-wrap:anywhere}@page{size:A3 landscape;margin:10mm}@media print{body{background:#fff}.page{width:400mm;height:275mm;margin:0;padding:7mm 10mm;break-after:page;page-break-after:always;print-color-adjust:exact;-webkit-print-color-adjust:exact}.page:last-child{break-after:auto;page-break-after:auto}footer{bottom:4mm}.title{margin-top:4mm}.no-print{display:none!important}}
  @media screen{.page{zoom:var(--preview-scale,1)}}
  .spread{grid-template-columns:minmax(0,2.4fr) minmax(0,1fr)}
  .page:nth-child(2) .block{margin-bottom:3mm}.page:nth-child(2) th,.page:nth-child(2) td{padding:1.6mm 2mm}.page:nth-child(2) .facts{margin:3mm 0 4mm}.page:nth-child(2) .check{padding:1.5mm 0}.page:nth-child(2) .logic{padding:1.5mm 0}.page:nth-child(2) .source{line-height:1.35}
  </style></head><body>
  <section class="page">${head(1,'A shared plan. A visible route. A human decision.')}<div class="spread"><div>${planVector(options)}<div class="flag ${route.available?'':'reject'}">${esc(route.exit)} is ${route.available?'available':'unavailable'} in the current scripted scenario. ${route.diagram_metres} m is the illustrated polyline; ${route.fixture_metres} m is the separate authored fixture distance. Neither is a verified real-world evacuation distance. Preview does not record an action.</div></div><div class="steps">${route.steps.map((s,i)=>`<article class="step"><i>0${i+1}</i><div><b>${esc(s.label)}</b><p>${esc(s.detail)}</p></div></article>`).join('')}<div class="flag">${assisted?'Assistance action recorded by facilitator. Verify that the intended people and backup arrangements are actually covered.':'Two assistance flags remain without a recorded assistance owner. Do not mark them accounted for from this preview.'}</div><div class="blank">Facilitator / plan reviewer / date</div></div></div>${foot(1)}</section>
  <section class="page">${head(2,'People, responsibilities and the rehearsal record.')}<div class="facts"><div><strong>84</strong><span>FICTIONAL REGISTER · NOT LIVE</span></div><div><strong>2</strong><span>ASSISTANCE FLAGS</span></div><div><strong>${coverage.unresolved.length}</strong><span>ACTIVE EVENTS WITHOUT A RESPONSE</span></div><div><strong>${state.approved?'Approved':'Draft'}</strong><span>HUMAN REVIEW STATUS</span></div></div>
  <div class="columns"><div><section class="block"><h2>Who is responsible?</h2><table><thead><tr><th>Role</th><th>Named exercise owner</th><th>Check</th></tr></thead><tbody>${BUILDING.roles.map(r=>`<tr><td>${esc(r.label)}</td><td>${esc(r.person || (assisted?'S. Tan · recorded assistance lead':'UNASSIGNED'))}</td><td>□ Confirm</td></tr>`).join('')}</tbody></table><p>Assistance details, individual consent, appropriate equipment and backup coverage require a qualified person. No medical capability is inferred.</p></section><section class="block"><h2>What does the plan actually show?</h2><table><thead><tr><th>Item</th><th>Location / inventory ID</th><th>Check</th></tr></thead><tbody>${SPATIAL_EQUIPMENT.map(e=>`<tr><td>${e.symbol} · ${esc(e.type)}</td><td>${esc(e.room)}<br/><span class="toolmeta">${esc(e.id)}</span></td><td>□ Inspect</td></tr>`).join('')}</tbody></table><p>The detector signal is scripted near 7-E. Equipment symbols do not establish serviceability, adequacy or permission to operate equipment.</p></section><section class="block"><h2>Account for people, not just actions.</h2><table><thead><tr><th>Zone</th><th>Register</th><th>Assistance</th><th>Observed at assembly</th></tr></thead><tbody>${Object.values(ZONES).map(z=>`<tr><td>${esc(z.label)}</td><td>${z.occupants}</td><td>${z.assisted}</td><td>_____ / not verified</td></tr>`).join('')}</tbody></table></section></div>
  <div><section class="block"><h2>The decision in four checks</h2>${route.logic.map(l=>`<div class="logic"><b>${l.label.toUpperCase()}</b><p>${esc(l.text)}</p></div>`).join('')}</section><section class="block"><h2>Run the tabletop, then review it.</h2>${CHECKLISTS.before.map(s=>`<div class="check">${esc(s)}</div>`).join('')}<div class="check">Introduce one scripted event. Ask each owner to state the intended response; record only what was observed.</div><div class="check">Reconcile the people register at the designated assembly location in the approved plan.</div><div class="check">Debrief gaps. Assign an improvement owner, due date and closure evidence. Keep final approval human.</div></section><section class="block"><h2>Snapshot, not a completion claim</h2><p><b>Events:</b> ${state.injectIds.length?state.injectIds.map(id=>esc(INJECTS[id]?.title||id)).join(' · '):'None introduced'}</p><p><b>Recorded actions:</b> ${state.decisions.length?state.decisions.map(d=>esc(ACTIONS[d.actionId]?.label||d.actionId)).join(' · '):'None'}</p><p><b>Unresolved:</b> ${coverage.unresolved.length?coverage.unresolved.map(g=>esc(g.label)).join(' · '):'No missing response to active events. This is not a safety rating.'}</p><div class="blank">Observed issue / improvement owner / due date</div></section><p class="source">Planning context: SCDF Emergency Response Plan resources, scdf.gov.sg/fire-safety-services-listing/emergency-response-plan. Muster is not affiliated with SCDF and this pack is not an approved ERP. 3D height, openings, furniture and route geometry are inferred from a fictional drawing.</p></div></div>${foot(2)}</section>
  </body></html>`;
}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);}
export function openDrillPack(options) {
  const previous=document.querySelector('#printPackDialog');
  previous?.close();previous?.remove();
  const dialog=document.createElement('dialog');dialog.id='printPackDialog';dialog.className='print-pack-dialog';
  dialog.innerHTML=`<header><div><strong>Floor 07 · drill pack</strong><span>Vector plan + two A3 pages · snapshot of this drill</span></div><nav><button id="printPDF" type="button">Print / Save PDF</button><button id="savePlanSVG" type="button">Vector SVG ↓</button><button id="savePlanPNG" type="button">5500 px PNG ↓</button><button id="closePrintPack" type="button">Close</button></nav></header><p id="printPackStatus">For a crisp PDF, select A3 landscape and disable browser headers/footers. Training only, not emergency signage.</p><iframe id="printPackFrame" title="Printable Floor 07 drill plan and facilitator instructions"></iframe>`;
  document.body.append(dialog); const frame=dialog.querySelector('iframe');
  const fitPreview=()=>frame.contentDocument?.documentElement?.style.setProperty('--preview-scale',String(Math.min(1,Math.max(.1,(frame.clientWidth-24)/(400*96/25.4)))));
  frame.addEventListener('load',fitPreview);
  const observer=new ResizeObserver(fitPreview);observer.observe(frame);
  dialog.addEventListener('close',()=>observer.disconnect(),{once:true});
  frame.srcdoc=drillPackHTML(options);
  dialog.showModal();
  dialog.querySelector('#closePrintPack').onclick=()=>dialog.close();
  dialog.querySelector('#printPDF').onclick=()=>{frame.contentWindow.focus();frame.contentWindow.print();};
  dialog.querySelector('#savePlanSVG').onclick=()=>download(new Blob([planVector(options)],{type:'image/svg+xml'}),'muster-F07-training-plan.svg');
  dialog.querySelector('#savePlanPNG').onclick=async()=>{
    const b=dialog.querySelector('#savePlanPNG'),status=dialog.querySelector('#printPackStatus');b.disabled=true;status.textContent='Rendering the vector plan at 5500 × 4250 pixels…';
    const url=URL.createObjectURL(new Blob([planVector(options)],{type:'image/svg+xml'}));
    try {const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=5500;canvas.height=4250;canvas.getContext('2d').drawImage(image,0,0,5500,4250);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Image export unavailable');download(blob,'muster-F07-training-plan-5500.png');status.textContent='5500 × 4250 PNG prepared. The SVG and PDF remain resolution-independent.';}catch(e){status.textContent=`PNG export failed: ${e.message}. Use Vector SVG instead.`;}finally{URL.revokeObjectURL(url);b.disabled=false;}
  };
}
